# The keys of the inputs and outputs dictionaries, as well as the file names should follow the camelCase notation.

inputs = {}

inputs["ZoneCodesFile"]           = "./HARMONY_LUTI_TUR/external-data/TUR_ZoneCodes.csv"
inputs["ZonesCoordinates"]        = "./HARMONY_LUTI_TUR/external-data/zones_data_coordinates.csv"
inputs["IntrazoneDist"]           = "./HARMONY_LUTI_TUR/external-data/intrazone_distances.csv"

inputs["CijCarODZones2019"]       = "./HARMONY_LUTI_TUR/external-data/Matrices/2019_Time_Car_270_270(min).csv"
inputs["CijCarODZones2030"]       = "./HARMONY_LUTI_TUR/external-data/Matrices/2030_Time_Car_270_270(min).csv"
inputs["CijCarPrimary2019"]       = "./HARMONY_LUTI_TUR/external-data/Matrices/2019_Time_Car_PrimarySchool_270_354(min).csv"
inputs["CijCarPrimary2030"]       = "./HARMONY_LUTI_TUR/external-data/Matrices/2030_Time_Car_PrimarySchool_270_354(min).csv"
inputs["CijCarMiddle2019"]        = "./HARMONY_LUTI_TUR/external-data/Matrices/2019_Time_Car_MiddleSchool_270_164(min).csv"
inputs["CijCarMiddle2030"]        = "./HARMONY_LUTI_TUR/external-data/Matrices/2030_Time_Car_MiddleSchool_270_164(min).csv"
inputs["CijCarHigh2019"]          = "./HARMONY_LUTI_TUR/external-data/Matrices/2019_Time_Car_HighSchool_270_216(min).csv"
inputs["CijCarHigh2030"]          = "./HARMONY_LUTI_TUR/external-data/Matrices/2030_Time_Car_HighSchool_270_216(min).csv"
inputs["CijCarUni2019"]           = "./HARMONY_LUTI_TUR/external-data/Matrices/2019_Time_Car_Uni_270_18(min).csv"
inputs["CijCarUni2030"]           = "./HARMONY_LUTI_TUR/external-data/Matrices/2030_Time_Car_Uni_270_18(min).csv"
inputs["CijCarHospitals2019"]     = "./HARMONY_LUTI_TUR/external-data/Matrices/2019_Time_Car_Hospitals_270x50(min).csv"
inputs["CijCarHospitals2030"]     = "./HARMONY_LUTI_TUR/external-data/Matrices/2030_Time_Car_Hospitals_270x47(min).csv"

inputs["CijBusODZones2019"]       = "./HARMONY_LUTI_TUR/external-data/Matrices/2019_Time_Bus_270_270(min).csv"
inputs["CijBusODZones2030"]       = "./HARMONY_LUTI_TUR/external-data/Matrices/2030_Time_Bus_270_270(min).csv"
inputs["CijBusPrimary2019"]       = "./HARMONY_LUTI_TUR/external-data/Matrices/2019_Time_Bus_PrimarySchool_270_354(min).csv"
inputs["CijBusPrimary2030"]       = "./HARMONY_LUTI_TUR/external-data/Matrices/2030_Time_Bus_PrimarySchool_270_354(min).csv"
inputs["CijBusMiddle2019"]        = "./HARMONY_LUTI_TUR/external-data/Matrices/2019_Time_Bus_MiddleSchool_270_164(min).csv"
inputs["CijBusMiddle2030"]        = "./HARMONY_LUTI_TUR/external-data/Matrices/2030_Time_Bus_MiddleSchool_270_164(min).csv"
inputs["CijBusHigh2019"]          = "./HARMONY_LUTI_TUR/external-data/Matrices/2019_Time_Bus_HighSchool_270_216(min).csv"
inputs["CijBusHigh2030"]          = "./HARMONY_LUTI_TUR/external-data/Matrices/2030_Time_Bus_HighSchool_270_216(min).csv"
inputs["CijBusUni2019"]           = "./HARMONY_LUTI_TUR/external-data/Matrices/2019_Time_Bus_Uni_270_18(min).csv"
inputs["CijBusUni2030"]           = "./HARMONY_LUTI_TUR/external-data/Matrices/2030_Time_Bus_Uni_270_18(min).csv"
inputs["CijBusHospitals2019"]     = "./HARMONY_LUTI_TUR/external-data/Matrices/2019_Time_Bus_Hospitals_270x50(min).csv"
inputs["CijBusHospitals2030"]     = "./HARMONY_LUTI_TUR/external-data/Matrices/2030_Time_Bus_Hospitals_270x47(min).csv"

inputs["CijRailODZones2019"]      = "./HARMONY_LUTI_TUR/external-data/Matrices/2019_Time_Rail_270_270(min).csv"
inputs["CijRailODZones2030"]      = "./HARMONY_LUTI_TUR/external-data/Matrices/2030_Time_Rail_270_270(min).csv"
inputs["CijRailPrimary2019"]      = "./HARMONY_LUTI_TUR/external-data/Matrices/2019_Time_Rail_PrimarySchool_270_354(min).csv"
inputs["CijRailPrimary2030"]      = "./HARMONY_LUTI_TUR/external-data/Matrices/2030_Time_Rail_PrimarySchool_270_354(min).csv"
inputs["CijRailMiddle2019"]       = "./HARMONY_LUTI_TUR/external-data/Matrices/2019_Time_Rail_MiddleSchool_270_164(min).csv"
inputs["CijRailMiddle2030"]       = "./HARMONY_LUTI_TUR/external-data/Matrices/2030_Time_Rail_MiddleSchool_270_164(min).csv"
inputs["CijRailHigh2019"]         = "./HARMONY_LUTI_TUR/external-data/Matrices/2019_Time_Rail_HighSchool_270_216(min).csv"
inputs["CijRailHigh2030"]         = "./HARMONY_LUTI_TUR/external-data/Matrices/2030_Time_Rail_HighSchool_270_216(min).csv"
inputs["CijRailUni2019"]          = "./HARMONY_LUTI_TUR/external-data/Matrices/2019_Time_Rail_Uni_270_18(min).csv"
inputs["CijRailUni2030"]          = "./HARMONY_LUTI_TUR/external-data/Matrices/2030_Time_Rail_Uni_270_18(min).csv"
inputs["CijRailHospitals2019"]    = "./HARMONY_LUTI_TUR/external-data/Matrices/2019_Time_Rail_Hospitals_270x50(min).csv"
inputs["CijRailHospitals2030"]    = "./HARMONY_LUTI_TUR/external-data/Matrices/2030_Time_Rail_Hospitals_270x47(min).csv"

inputs["ObsCarCommuting"]         = "./HARMONY_LUTI_TUR/external-data/Matrices/Car_Commuting_270x270.csv"
inputs["ObsBusCommuting"]         = "./HARMONY_LUTI_TUR/external-data/Matrices/Bus_Commuting_270x270.csv"
inputs["ObsRailCommuting"]        = "./HARMONY_LUTI_TUR/external-data/Matrices/Rail_Commuting_270x270.csv"

inputs["DataPopulation2019"]      = "./HARMONY_LUTI_TUR/external-data/Population_2019.csv"
inputs["DataPopulation2030"]      = "./HARMONY_LUTI_TUR/external-data/Population_2030.csv"
inputs["DataHospitals2019"]       = "./HARMONY_LUTI_TUR/external-data/Hospitals/hospitals_2019.csv"
inputs["DataHospitals2030"]       = "./HARMONY_LUTI_TUR/external-data/Hospitals/hospitals_2030.csv"
inputs["DataEmployment2019"]      = "./HARMONY_LUTI_TUR/external-data/Employment/Employed_2019.csv"
inputs["DataEmployment2030"]      = "./HARMONY_LUTI_TUR/external-data/Employment/Employed_2030.csv"
inputs["HhFloorspace2019"]        = "./HARMONY_LUTI_TUR/external-data/Employment/Residential_Floor_Space.csv"

inputs["PrimaryCapacity2019"]     = "./HARMONY_LUTI_TUR/external-data/Schools/primary_capacity.csv"
inputs["MiddleCapacity2019"]      = "./HARMONY_LUTI_TUR/external-data/Schools/middle_capacity.csv"
inputs["HighCapacity2019"]        = "./HARMONY_LUTI_TUR/external-data/Schools/high_schools_capacity.csv"
inputs["UniCapacity2019"]         = "./HARMONY_LUTI_TUR/external-data/Schools/unis_capacity_2019.csv"
inputs["UniCapacity2030"]         = "./HARMONY_LUTI_TUR/external-data/Schools/unis_capacity_2030.csv"

inputs["DataSchoolsPupils2019"]   = "./HARMONY_LUTI_TUR/external-data/Schools/Pupil_2019.csv"
inputs["DataSchoolsPupils2030"]   = "./HARMONY_LUTI_TUR/external-data/Schools/Pupil_2030.csv"
inputs["DataUniStudents2019"]     = "./HARMONY_LUTI_TUR/external-data/Schools/Uni_students_2019.csv"
inputs["DataUniStudents2030"]     = "./HARMONY_LUTI_TUR/external-data/Schools/Uni_students_2030.csv"

inputs["DataZonesShapefile"]      = "./HARMONY_LUTI_TUR/external-data/geography/Modello_TRT_reshaped_zone.shp"

inputs["RoadNetworkShapefile"]    = "./HARMONY_LUTI_TUR/external-data/geography/Main_roads.shp"
inputs["ZonesCentroidsShapefile"] = "./HARMONY_LUTI_TUR/external-data/geography/Zones_centroids.shp"

outputs = {}

outputs["JobsAccessibility2019"]            = "./Outputs-Turin/jobs_accessibility_2019.csv"
outputs["JobsAccessibility2030"]            = "./Outputs-Turin/jobs_accessibility_2030.csv"
outputs["HousingAccessibility2019"]         = "./Outputs-Turin/housing_accessibility_2019.csv"
outputs["HousingAccessibility2030"]         = "./Outputs-Turin/housing_accessibility_2030.csv"
outputs["JobsDjOi2019"]                     = "./Outputs-Turin/Jobs_DjOi_2019.csv"
outputs["JobsDjOi2030"]                     = "./Outputs-Turin/Jobs_DjOi_2030.csv"
outputs["JobsProbTijRoads2019"]             = "./Outputs-Turin/jobsProbTij_roads_2019.csv"
outputs["JobsProbTijRoads2030"]             = "./Outputs-Turin/jobsProbTij_roads_2030.csv"
outputs["JobsProbTijBus2019"]               = "./Outputs-Turin/jobsProbTij_bus_2019.csv"
outputs["JobsProbTijBus2030"]               = "./Outputs-Turin/jobsProbTij_bus_2030.csv"
outputs["JobsProbTijRail2019"]              = "./Outputs-Turin/jobsProbTij_rail_2019.csv"
outputs["JobsProbTijRail2030"]              = "./Outputs-Turin/jobsProbTij_rail_2030.csv"
outputs["JobsTijRoads2019"]                 = "./Outputs-Turin/jobsTij_roads_2019.csv"
outputs["JobsTijRoads2030"]                 = "./Outputs-Turin/jobsTij_cars_2030.csv"
outputs["JobsTijBus2019"]                   = "./Outputs-Turin/jobsTij_bus_2019.csv"
outputs["JobsTijBus2030"]                   = "./Outputs-Turin/jobsTij_bus_2030.csv"
outputs["JobsTijRail2019"]                  = "./Outputs-Turin/jobsTij_rail_2019.csv"
outputs["JobsTijRail2030"]                  = "./Outputs-Turin/jobsTij_rail_2030.csv"
outputs["ArrowsFlowsRoads2019"]             = "./Outputs-Turin/flows_2019_roads.geojson"
outputs["ArrowsFlowsRoads2030"]             = "./Outputs-Turin/flows_2030_roads.geojson"
outputs["ArrowsFlowsBus2019"]               = "./Outputs-Turin/flows_2019_bus.geojson"
outputs["ArrowsFlowsBus2030"]               = "./Outputs-Turin/flows_2030_bus.geojson"
outputs["ArrowsFlowsRail2019"]              = "./Outputs-Turin/flows_2019_rail.geojson"
outputs["ArrowsFlowsRail2030"]              = "./Outputs-Turin/flows_2030_rail.geojson"

outputs["PrimaryProbPijRoads2019"]         = "./Outputs-Turin/primaryProbPij_roads_2019.csv"
outputs["PrimaryProbPijRoads2030"]         = "./Outputs-Turin/primaryProbPij_roads_2030.csv"
outputs["PrimaryProbPijBus2019"]           = "./Outputs-Turin/primaryProbPij_bus_2019.csv"
outputs["PrimaryProbPijBus2030"]           = "./Outputs-Turin/primaryProbPij_bus_2030.csv"
outputs["PrimaryProbPijRail2019"]          = "./Outputs-Turin/primaryProbPij_rail_2019.csv"
outputs["PrimaryProbPijRail2030"]          = "./Outputs-Turin/primaryProbPij_rail_2030.csv"
outputs["PrimaryPijRoads2019"]             = "./Outputs-Turin/primaryPij_roads_2019.csv"
outputs["PrimaryPijRoads2030"]             = "./Outputs-Turin/primaryPij_roads_2030.csv"
outputs["PrimaryPijBus2019"]               = "./Outputs-Turin/primaryPij_bus_2019.csv"
outputs["PrimaryPijBus2030"]               = "./Outputs-Turin/primaryPij_bus_2030.csv"
outputs["PrimaryPijRail2019"]              = "./Outputs-Turin/primaryPij_rail_2019.csv"
outputs["PrimaryPijRail2030"]              = "./Outputs-Turin/primaryPij_rail_2030.csv"

outputs["MiddleProbPijRoads2019"]          = "./Outputs-Turin/middleProbPij_roads_2019.csv"
outputs["MiddleProbPijRoads2030"]          = "./Outputs-Turin/middleProbPij_roads_2030.csv"
outputs["MiddleProbPijBus2019"]            = "./Outputs-Turin/middleProbPij_bus_2019.csv"
outputs["MiddleProbPijBus2030"]            = "./Outputs-Turin/middleProbPij_bus_2030.csv"
outputs["MiddleProbPijRail2019"]           = "./Outputs-Turin/middleProbPij_rail_2019.csv"
outputs["MiddleProbPijRail2030"]           = "./Outputs-Turin/middleProbPij_rail_2030.csv"
outputs["MiddlePijRoads2019"]              = "./Outputs-Turin/middlePij_roads_2019.csv"
outputs["MiddlePijRoads2030"]              = "./Outputs-Turin/middlePij_roads_2030.csv"
outputs["MiddlePijBus2019"]                = "./Outputs-Turin/middlePij_bus_2019.csv"
outputs["MiddlePijBus2030"]                = "./Outputs-Turin/middlePij_bus_2030.csv"
outputs["MiddlePijRail2019"]               = "./Outputs-Turin/middlePij_rail_2019.csv"
outputs["MiddlePijRail2030"]               = "./Outputs-Turin/middlePij_rail_2030.csv"

outputs["HighProbPijRoads2019"]            = "./Outputs-Turin/highProbPij_roads_2019.csv"
outputs["HighProbPijRoads2030"]            = "./Outputs-Turin/highProbPij_roads_2030.csv"
outputs["HighProbPijBus2019"]              = "./Outputs-Turin/highProbPij_bus_2019.csv"
outputs["HighProbPijBus2030"]              = "./Outputs-Turin/highProbPij_bus_2030.csv"
outputs["HighProbPijRail2019"]             = "./Outputs-Turin/highProbPij_rail_2019.csv"
outputs["HighProbPijRail2030"]             = "./Outputs-Turin/highProbPij_rail_2030.csv"
outputs["HighPijRoads2019"]                = "./Outputs-Turin/highPij_roads_2019.csv"
outputs["HighPijRoads2030"]                = "./Outputs-Turin/highPij_roads_2030.csv"
outputs["HighPijBus2019"]                  = "./Outputs-Turin/highPij_bus_2019.csv"
outputs["HighPijBus2030"]                  = "./Outputs-Turin/highPij_bus_2030.csv"
outputs["HighPijRail2019"]                 = "./Outputs-Turin/highPij_rail_2019.csv"
outputs["HighPijRail2030"]                 = "./Outputs-Turin/highPij_rail_2030.csv"

outputs["UniProbPijRoads2019"]             = "./Outputs-Turin/uniProbPij_roads_2019.csv"
outputs["UniProbPijRoads2030"]             = "./Outputs-Turin/uniProbPij_roads_2030.csv"
outputs["UniProbPijBus2019"]               = "./Outputs-Turin/uniProbPij_bus_2019.csv"
outputs["UniProbPijBus2030"]               = "./Outputs-Turin/uniProbPij_bus_2030.csv"
outputs["UniProbPijRail2019"]              = "./Outputs-Turin/uniProbPij_rail_2019.csv"
outputs["UniProbPijRail2030"]              = "./Outputs-Turin/uniProbPij_rail_2030.csv"
outputs["UniPijRoads2019"]                 = "./Outputs-Turin/uniPij_roads_2019.csv"
outputs["UniPijRoads2030"]                 = "./Outputs-Turin/uniPij_roads_2030.csv"
outputs["UniPijBus2019"]                   = "./Outputs-Turin/uniPij_bus_2019.csv"
outputs["UniPijBus2030"]                   = "./Outputs-Turin/uniPij_bus_2030.csv"
outputs["UniPijRail2019"]                  = "./Outputs-Turin/uniPij_rail_2019.csv"
outputs["UniPijRail2030"]                  = "./Outputs-Turin/uniPij_rail_2030.csv"

outputs["HospitalsProbPijRoads2019"]       = "./Outputs-Turin/hospitalsProbHij_roads_2030.csv"
outputs["HospitalsProbPijRoads2030"]       = "./Outputs-Turin/hospitalsProbHij_roads_2030.csv"
outputs["HospitalsProbPijBus2019"]         = "./Outputs-Turin/hospitalsProbHij_bus_2019.csv"
outputs["HospitalsProbPijBus2030"]         = "./Outputs-Turin/hospitalsProbHij_bus_2030.csv"
outputs["HospitalsProbPijRail2019"]        = "./Outputs-Turin/hospitalsProbHij_rail_2019.csv"
outputs["HospitalsProbPijRail2030"]        = "./Outputs-Turin/hospitalsProbHij_rail_2030.csv"
outputs["HospitalsPijRoads2019"]           = "./Outputs-Turin/hospitalsHij_roads_2019.csv"
outputs["HospitalsPijRoads2030"]           = "./Outputs-Turin/hospitalsHij_roads_2030.csv"
outputs["HospitalsPijBus2019"]             = "./Outputs-Turin/hospitalsHij_bus_2019.csv"
outputs["HospitalsPijBus2030"]             = "./Outputs-Turin/hospitalsHij_bus_2030.csv"
outputs["HospitalsPijRail2019"]            = "./Outputs-Turin/hospitalsHij_rail_2019.csv"
outputs["HospitalsPijRail2030"]            = "./Outputs-Turin/hospitalsHij_rail_2030.csv"

outputs["MapPopChange20192030"]             = "./Outputs-Turin/pop_change_19-30.png"
outputs["MapHousingAccChange20192030Roads"] = "./Outputs-Turin/HA_change_19-30_roads.png"
outputs["MapHousingAccChange20192030Bus"]   = "./Outputs-Turin/HA_change_19-30_bus.png"
outputs["MapHousingAccChange20192030Rail"]  = "./Outputs-Turin/HA_change_19-30_rail.png"
outputs["MapJobsAccChange20192030Roads"]    = "./Outputs-Turin/JA_change_19-30_roads.png"
outputs["MapJobsAccChange20192030Bus"]      = "./Outputs-Turin/JA_change_19-30_bus.png"
outputs["MapJobsAccChange20192030Rail"]     = "./Outputs-Turin/JA_change_19-30_rail.png"

outputs["MapResultsShapefile"]              = "./Outputs-Turin/TUR_results.shp"